swagger: '2.0'
info:
  title: Haushaltsbuch API
  description: Move your app forward with the Uber API
  version: "1.0.0"
# the domain of the service
host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /version:
    get:
      # operationId: getVersion
      # summary: Version des Backends
      # description: Der Endpunkt Version liefert die Version des Backends
      # tags:
      #    - Version
      produces:
        - application/json
      responses:
        200:
          description: Ein Version Objekt
          schema:
            $ref: "#/definitions/Version"

definitions:
  Version:
    type: object
    required:
      - buildId
      - scmId
    properties:
      buildId:
        type: string
        description: Identifikationsmerkmal des CI Build
      scmId:
        type: string
        description: Stand der Quellcodeverwaltung